export const text = {
  nav: '주요 내비게이션',
  browse: '둘러보기',
  makeCourse: '코스 만들기',
  premium: '프리미엄',
  mapButton: '지도 보기',
  eyebrow: '주말 자전거 코스',
  headline: '다음 라이딩을 계획해보세요',
  searchLabel: '어디로 가볼까요?',
  searchPlaceholder: '예시, 지역, 코스 검색',
  search: '검색',
  mapEyebrow: 'OpenStreetMap',
  mapTitle: '자전거 경로 탐색',
  close: '메인으로',
  layerLabel: '지도 레이어',
  defaultLayer: '일반 지도',
  bicycleLayer: '자전거도로',
  startPlace: '출발지',
  endPlace: '도착지',
  startPlaceholder: '출발지 검색',
  endPlaceholder: '도착지 검색',
  searchStart: '출발 검색',
  searchEnd: '도착 검색',
  reset: '초기화',
  routeHint: '지도를 두 번 클릭하거나 출발지와 도착지를 검색하세요.',
  bikeRoute: '자전거도로',
  shortestRoute: '최단경로',
  searching: '경로를 찾는 중...',
  routeReady: '경로 2개를 표시했습니다.',
  routeFailed: '경로를 찾지 못했습니다. 점을 더 가까이 지정해보세요.',
  noCycleways: '해당 경로에 자전거 도로가 없습니다.',
  searchFailed: '검색 결과가 없습니다.',
  regionLabel: '지역 선택',
  regionAll: '전체',
  community: '커뮤니티 활동',
  recentTitle: '최근 완주된 코스',
  recentAria: '최근 완주된 자전거 코스',
  distance: '거리',
  climb: '상승고도',
  time: '시간',
};

export const seoulCenter = [37.5665, 126.978];
export const KAKAO_API_KEY = '05e75b48c0dc04aecae7a772c0637656';

export const GU_LIST = [
  '강남구', '강동구', '강북구', '강서구', '관악구',
  '광진구', '구로구', '구리시', '금천구', '노원구',
  '도봉구', '동대문구', '동작구', '마포구', '서초구',
  '성동구', '성북구', '송파구', '양천구', '영등포구',
  '용산구', '은평구', '종로구', '중구', '중랑구',
];

export const tileLayers = {
  cyclemap: {
    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    attribution: '&copy; OpenStreetMap contributors',
  },
  mapnik: {
    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    attribution: '&copy; OpenStreetMap contributors',
  },
};

export const routes = [
  {
    title: '한강 노을 순환 코스',
    location: '서울, 반포대교',
    distance: '28.4 km',
    climb: '112 m',
    time: '1시간 24분',
    type: '시티 바이크',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '북한강 강변 라이딩',
    location: '경기 남양주',
    distance: '41.2 km',
    climb: '238 m',
    time: '2시간 08분',
    type: '로드 바이크',
    image: 'https://images.unsplash.com/photo-1471506480208-91b3a4cc78be?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '제주 해안 아침 코스',
    location: '제주 제주시',
    distance: '64.7 km',
    climb: '486 m',
    time: '3시간 35분',
    type: '투어링',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '양재천 회복 라이딩',
    location: '서울 강남',
    distance: '16.9 km',
    climb: '52 m',
    time: '48분',
    type: '전기 자전거',
    image: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '남산 업힐 반복 코스',
    location: '서울 중구',
    distance: '22.1 km',
    climb: '614 m',
    time: '1시간 42분',
    type: 'MTB',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '부산 바닷바람 코스',
    location: '부산 해운대',
    distance: '37.5 km',
    climb: '174 m',
    time: '1시간 56분',
    type: '로드 바이크',
    image: 'https://images.unsplash.com/photo-1494475673543-6a6a27143fc8?auto=format&fit=crop&w=900&q=80',
  },
];
